### PR TITLE
Lab 4

### PR DESCRIPTION
**Pull request by ingamusatova**
Hello! Eto vse, please, check!

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Inga.

1.29 I didn't find fix. Upload it, please.
1.31 I didn't find fix. Upload it, please.

3.1 👍 
3.10 👍 

Fix remarks till the Tuesday. Otherwise the mark for defence will be erased.

**Comment by ingamusatova** [comment]
Hello! I sent it to you...

**Comment by ingamusatova** [comment]
image

**Comment by NemirovichMark** [comment]
patch-5 was accepted

**Pull request closed without merging**
