### PR TITLE
Create 4_Lab

### PR DESCRIPTION
**Pull request by BrekotkinaKarina**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Karina.

1.17 Doesn't work. Min element have to shift all before to the right and come to the 1st position.
image

1.29 If min element in the last column, no need to delete anything.
image

3.1 Doesn't work
image

3.8 Doesn't work
image

Everything else is correct 👍 

P.S. cute and hilarious printings on the console :)

**Comment by BrekotkinaKarina** [comment]
//Task 17 
            #region
            Console.WriteLine("количество строк?");
            string stol = Console.ReadLine();
            Console.WriteLine("количество столбцов?");
            string strok = Console.ReadLine();
            string chisl;
            int stolb, stroka, chisl2, minBro;
            int.TryParse(stol, out stolb);
            int.TryParse(strok, out stroka);
            int[,] Bro = new int[stolb, stroka];
            int stl, stk;
            Console.WriteLine("Задайте значения внутри матрицы");
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    chisl = Console.ReadLine();
                    int.TryParse(chisl, out chisl2);
                    Bro[stl, stk] = chisl2;
                }
            }
            stl = 0;
            stk = 0;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                minBro = Bro[stl, 0];
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    if (Bro[stl, stk] < minBro)
                    {
                        minBro = (Bro[stl, stk]);
                        Bro[stl, 0] = minBro;
                    }
                }
            }
            stl = 0;
            stk = 0;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    Console.Write(Bro[stl, stk] + "\t");
                }
                Console.WriteLine();
            }
            Console.ReadLine();
            #endregion

            //Task 29
            #region
            Random Ff = new Random();
            int[,] F = new int[5, 7];
            int[,] new_F = new int[5, 6];
            int Fmin, f, f2, ff = 0;
            for (f = 0; f < F.GetLength(0); f++)//заполнение массива 
            {
                for (f2 = 0; f2 < F.GetLength(1); f2++)
                {
                    F[f, f2] = Ff.Next(-10, 10);
                    Console.Write(F[f, f2] + "\t");
                }
                Console.WriteLine();
            }
            f = 0;
            f2 = 0;
            Fmin = F[1, 0];
            for (f2 = 0; f2 < F.GetLength(1); f2++)//нахождение минимального массива
            {
                if (Math.Abs(F[1, f2]) < Fmin)
                {
                    Fmin = F[1, f2];
                    ff = f2 + 1;
                }
            }
            f2 = 0;
            f = 0;
            if (ff != F.GetLength(1))
            {
                for (f = 0; f < new_F.GetLength(0); f++)//заполнение нового
                {
                    for (f2 = 0; f2 < new_F.GetLength(1); f2++)
                    {
                        if (f != ff)
                        {
                            new_F[f, f2] = F[f, f2];
                        }
                        else
                        {
                            f2 = f2 + 1;
                        }
                    }
                }
            }
            f2 = 0;
            f = 0;
            for (f = 0; f < new_F.GetLength(0); f++)
            {
                for (f2 = 0; f2 < new_F.GetLength(1); f2++)
                {
                    Console.Write(F[f, f2] + "\t");
                }
                Console.WriteLine();
            }
            Console.ReadLine();
            #endregion 
            //LEVEL 3 
            //task 1 
            #region
            Random ryu = new Random();
            int[,] makima = new int[7, 5];
            int[] pochito = new int[7];
            int aki, power, hime, demon = 0, demon_2 = 0, minmin = 0;
            for (aki = 0; aki < makima.GetLength(0); aki++)
            {
                for (hime = 0; hime < makima.GetLength(1); hime++)
                {
                    makima[aki, hime] = ryu.Next(-10, 10);
                    Console.Write(makima[aki, hime] + "\t");
                }
                Console.WriteLine();
            }
            aki = 0;
            hime = 0;
            for (aki = 0; aki < makima.GetLength(0); aki++)
            {
                power = makima[aki, 0];
                for (hime = 0; hime < makima.GetLength(1); hime++)
                {
                    if (makima[aki, hime] < power)
                    {
                        power = makima[aki, hime];
                    }
                }
                pochito[aki] = power;
                Console.WriteLine("min of  " + aki + " line is " + power);
            }
            Console.WriteLine();
            power = 0;
            hime = 0;
            aki = 0;
            for (hime = 1; hime < 7 - 1; hime++)
            {
                if (pochito[hime] <= pochito[hime + 1])
                {
                    for (aki = 0; aki < 5; aki++)
                    {
                        power = makima[hime, aki];
                        makima[hime, aki] = makima[hime + 1, aki];
                        makima[hime + 1, aki] = power;
                    }
                    minmin = pochito[hime];
                    pochito[hime] = pochito[hime + 1];
                    pochito[hime + 1] = minmin;
                }
            }
            Console.WriteLine();
            aki = 0;
            hime = 0;
            for (aki = 0; aki < makima.GetLength(0); aki++)
            {
                for (hime = 0; hime < makima.GetLength(1); hime++)
                {
                    Console.Write(makima[aki, hime] + "\t");
                }
                Console.WriteLine();
            }
            aki = 0;
            hime = 0;
            for (aki = 0; aki < makima.GetLength(0); aki++)
            {
                power = makima[aki, 0];
                for (hime = 0; hime < makima.GetLength(1); hime++)
                {
                    if (makima[aki, hime] < power)
                    {
                        power = makima[aki, hime];
                    }
                }
                pochito[aki] = power;
                Console.WriteLine("min of  " + aki + " line is " + power);
            }
            Console.ReadLine();
            #endregion
             //Task 8
            #region
            Random ppl = new Random();
            int[,] people = new int[7, 5];
            int[] people_2 = new int[7];
            int white, black, mulat, mulat_2 = 0, boobies, boobies_2 = 0, white_2;
            for (white = 0; white < people.GetLength(0); white++)
            {
                for (black = 0; black < people.GetLength(1); black++)
                {
                    people[white, black] = ppl.Next(-10, 10);
                    Console.Write(people[white, black] + "\t");
                }
                Console.WriteLine();
            }
            white = 0;
            black = 0;
            for (white = 0; white < 7; white++)
            {
                mulat = 0;
                for (black = 0; black < 5; black++)
                {
                    if (people[white, black] > 0)
                    {
                        mulat = mulat + 1;
                    }
                    mulat_2 = mulat;
                    people_2[white] = mulat_2;
                }
                Console.WriteLine("positive nums " + mulat_2);
            }
            white = 0;
            black = 0;
            for (white = 0; white < people_2.Length - 1; white++)
            {
                if (people_2[white] < people_2[white + 1])
                {
                    for (boobies = 0; boobies < 5; boobies++)
                    {
                        black = people[white, boobies];
                        people[white, boobies] = people[white + 1, boobies];
                        people[white + 1, boobies] = black;

                    }
                    white_2 = people_2[white];
                    people_2[white] = people_2[white + 1];
                    people_2[white + 1] = white_2;
                }
            }
            Console.WriteLine();
            Console.WriteLine("GO! GO! GO!");
            black = 0;
            white = 0;
            for (white = 0; white < people.GetLength(0); white++)
            {
                for (black = 0; black < people.GetLength(1); black++)
                {
                    Console.Write(people[white, black] + "\t");
                }
                Console.WriteLine();
            }
            Console.ReadLine();
            #endregion

**Comment by NemirovichMark** [comment]
1.17 Still doesn't work
image

1.29  Still doesn't work
image

**Comment by NemirovichMark** [comment]
Hello Karina.
Fix remarks till the Tuesday. Otherwise the mark for defence will be erased.

**Comment by BrekotkinaKarina** [comment]
//Task 17 
            #region
            Random info = new Random();
            int chisl2 = 0, minBro;
            int[,] Bro = new int[5, 5];
            int[,] Bro_2 = new int[5, 5];
            int stl, stk;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    Bro[stl, stk] = info.Next(-10, 10);
                    Console.Write(Bro[stl, stk] + "\t");
                }
                Console.WriteLine();
            }
            stl = 0;
            stk = 0;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    Bro_2[stl, stk] = Bro[stl, stk];
                }
            }
            stl = 0;
            stk = 0;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                minBro = Bro[stl, 0];
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    if (Bro[stl, stk] < minBro)
                    {
                        minBro = (Bro[stl, stk]);
                        chisl2 = stk;
                    }
                    Bro[stl, 0] = minBro;
                }
                stk = 0;
                for (stk = chisl2; stk > 0; stk--)
                {
                    Bro[stl, stk] = Bro_2[stl, stk - 1];
                }
            }
            Console.WriteLine();
            stl = 0;
            stk = 0;
            for (stl = 0; stl < Bro.GetLength(0); stl++)
            {
                for (stk = 0; stk < Bro.GetLength(1); stk++)
                {
                    Console.Write(Bro[stl, stk] + "\t");
                }
                Console.WriteLine();
            }
            Console.ReadLine();
            #endregion
            
            //Task 29
            #region
            Random Ff = new Random();
            int[,] F = new int[5, 7];
            int[,] new_F = new int[5, 6];
            int Fmin, f, f2, ff = 0;
            for (f = 0; f < F.GetLength(0); f++)//заполнение массива 
            {
                for (f2 = 0; f2 < F.GetLength(1); f2++)
                {
                    F[f, f2] = Ff.Next(-10, 10);
                    Console.Write(F[f, f2] + "\t");
                }
                Console.WriteLine();
            }
            f = 0;
            f2 = 0;
            Fmin = F[1, 0];
            for (f2 = 0; f2 < F.GetLength(1); f2++)//нахождение минимального массива
            {
                if (Math.Abs(F[1, f2]) < Math.Abs(Fmin))
                {
                    Fmin = F[1, f2];
                    ff = f2 + 1;
                }
            }
            Console.WriteLine(Fmin + "    MIIIIIIIIIIIIN");
            f2 = 0;
            f = 0;
            if (ff != F.GetLength(1))
            {
                for (f = 0; f < new_F.GetLength(0); f++)//заполнение нового
                {
                    for (f2 = 0; f2 < new_F.GetLength(1); f2++)
                    {
                        if (f != ff)
                        {
                            new_F[f, f2] = F[f, f2];
                        }
                        else
                        {
                            f2 = f2 + 1;
                        }
                    }
                }
            }
            Console.WriteLine();
            f2 = 0;
            f = 0;
            for (f = 0; f < new_F.GetLength(0); f++)
            {
                for (f2 = 0; f2 < new_F.GetLength(1); f2++)
                {
                    Console.Write(F[f, f2] + "\t");
                }
                Console.WriteLine();
            }
            Console.ReadLine();
            #endregion

**Comment by NemirovichMark** [comment]
Hello.

1.17 👍 
1.29 Still doesn't work.
image

Defend has erased :(

**Comment by BrekotkinaKarina** [comment]
#region 29
            int[,] F = new int[5, 7]
            {
                {2, 3, 1, 5, 0, 5, 1},
                {5, 4, 8, 6, 1, -3, 13},
                {2, 2, 9, 1, -5, -4, 2},
                {0, 4, 1, 5, 23, 7, 12},
                {14,-2, 1,-12,1, 5, 5},
            };
            int min3 = F[1, 0], ff = 0;
            for (int i = 0; i < F.GetLength(1); i++)
            {
                if (min3 > Math.Abs(F[1, i]))
                {
                    min3 = Math.Abs(F[1, i]);
                    ff = i+1;
                }
            }
            if (ff == 6)
            {
                for (int i = 0; i < F.GetLength(0); i++)
                {
                    for (int j = 0; j < F.GetLength(1); j++)
                    {
                        Console.Write(F[i, j] + "\t");
                    }
                    Console.WriteLine();
                }
            }
            else
            {
                int[,] FF = new int[5, 6];
                for (int i = 0; i < F.GetLength(0); i++)
                {
                    int ind10 = 0;
                    for (int j = 0; j < F.GetLength(1); j++)
                    {
                        if (j == ff + 1)
                        {
                            ind10 -= 1;
                        }
                        else
                        {
                            FF[i, ind10] = F[i, j];
                        }
                        ind10 += 1;
                    }
                }
                for (int i = 0; i < FF.GetLength(0); i++)
                {
                    for (int j = 0; j < FF.GetLength(1); j++)
                    {
                        Console.Write(FF[i, j] + "\t");
                    }
                    Console.WriteLine();
                }
            }
            Console.WriteLine();
            #endregion

**Comment by NemirovichMark** [comment]
Good job!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
