### PR TITLE
pls check

### PR DESCRIPTION
**Pull request by zzmtsvv**
can I defend lab not only on my group's seminar?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello. Yes, you can. You can come with 22-17 or 22-20 groups.

1.3 System.ArgumentOutOfRangeException: Index was out of range.
(I inputed less than 4 numbers in the row)

Fix this problem in all solutions.

1.6 In the class I will ask you do not use it:
                    int min_idx = Array.IndexOf(row, row.Min());

1.29 Remove duplicating

2.7 Something wrong (why columns' amount less than should?):
image

3.4 1 should be instead of 0. And main diagonal included.

3.11 Why did you use Dictionary there? I accept this solution, but seems like to hammer a nail by paver.

**Comment by zzmtsvv** [comment]
Can I get 5 on programming before exam in another way? For example, if I show you one of my projects on Machine Learning

**Comment by NemirovichMark** [comment]
Nope

**Comment by zzmtsvv** [comment]
so what if I will win yandex cup?

**Comment by NemirovichMark** [comment]
This means that you are a good programmer and such tasks should be easy for you.
Do you know python? Than study of strict OOP compiled language (as C# is) will be useful for you.
If you won using C++ than C# learning should be elementary.

My job is help you to get useful skills and habits. As much different task you will do, as better you will.

**Comment by zzmtsvv** [comment]
I mean, will I get an automatic "5" if I will win yandex cup in a month

**Comment by NemirovichMark** [comment]
Ask it from lecturer. I cannot (and do not wish) to give you 5 for your non-class activity. But it is good achievement, that can help you in the future.

**Comment by zzmtsvv** [comment]
"1.29 Remove duplicating"
duplicating of what?

btw I used dictionary in 3.11 in terms of generalisation (n, m can be very large, so Dictionary with constant time complexity of getting the value from it would be appropriate)

**Comment by NemirovichMark** [comment]
Hello Alexey. 

1.29
if (j_min == m - 1)
                {
                    for (int i = 0; i < n; i++)
                    {
                        string line = "";
                        for (int j = 0; j < m; j++)
                        {
                            line += A[i, j];
                            line += " ";
                        }
                        Console.WriteLine(line);
                    }
                }
And last cycle. 
You no need actually to separate program by if(j_min == m - 1)
You can break the cycle after start, isn't it?
In the end you have to resize an array if the column was removed! Not just print m-1 column.

3.11 Can be solved by array (it consume less stack memory). Meanwhile it consume less processor time. But sinsce your current program very small, disadvantage by memory more than benefit by speed. 
I, actually, glad to see that you know how does it work, and do not ask you to make only with arrays. Use different tools, as you did. I just concern that you know how does it work or not.

**Comment by zzmtsvv** [comment]
I don't quite understand your comment - I separated the code with if statement in order non to use additional matrix for the case j_min = m - 1

"You can break the cycle after start, isn't it?" - I don't understand
" you have to resize an array if the column was removed! Not just print m-1 column." - I don't understand you, I removed the column as the task obey and print the matrix

**Comment by NemirovichMark** [comment]
Oh, I see you (finally).
That you provide either input matrix without changes or another matrix, based on input, but shorter.
Hm... okay, we can call it "matrix with deleted element". I expected to see that inputed matxir would be shorter. Sorry, what you did have a sense. You can leave it as it is.

**Comment by zzmtsvv** [comment]
thank you!
I have fixed another problems

**Comment by zzmtsvv** [comment]
can you please open access to 5th lab? I've already done it

**Comment by NemirovichMark** [comment]
Yes, excuse me for delay.

**Comment by NemirovichMark** [comment]
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
