### PR TITLE
Create lab4

### PR DESCRIPTION
**Pull request by lxncort**
i did!!<3

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Maria.

1.29 You did't REMOVE the column.
image

3.10 Do not use 3-nested loop, please.
image

Everything else is correct 👍

**Comment by lxncort** [comment]
i fixed <3

**Comment by NemirovichMark** [comment]
Hello Maria.

Acually it would be better just print a non-changed matrix that write the message. But okay, I accept it.

What about 3.10?

**Comment by lxncort** [comment]
i fixed 3.10

**Comment by NemirovichMark** [comment]
Well done!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
