### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by AleksandrZyuzyukin**
Hello Mark!
I did it.
Could you please check it?

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Aelxandr.

1.12 You didn't remove lines. You shift and hide them. Array have to become less!
image

3.11 You still have zeros in the matrix
image

**Comment by AleksandrZyuzyukin** [comment]
Hello Mark!
I fixed it. Could you please check?

**Comment by AleksandrZyuzyukin** [comment]
Good evening, Mark!
Could you please check fixed lab?
Have a wonderful weekend!

**Comment by NemirovichMark** [comment]
Hello, Sorry, miss your work at Saturday. But it is good, so it's not a problem.

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms:
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
