### PR TITLE
4 Lab

### PR DESCRIPTION
**Pull request by vladimirsah**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Vladimir.

1.17 You changes 2 elements, but the task is move element to the begining
image

1.29 2nd line have index 1, actually. And if min element in the last column, there is nothing to delete
image

3.10 Do not use 3-nested loops.
image

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
Hello Vladimir.

1.17 👍 
1.29 👍 

3.10 Nope. In the Array.Sort 2 loops are used.
image

**Comment by vladimirsah** [comment]
Array.sort здесь используется для сортировки массива b, не матрицы a

**Comment by NemirovichMark** [comment]
I understand. But it is still 3-nested loops in a total.

**Comment by NemirovichMark** [comment]
Cool! 👍 
Percentage divison is a poverful things, mostly underrated. 

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
