### PR TITLE
Lab4 done

### PR DESCRIPTION
**Pull request by MichailSitnikov**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Michail.

1.17 IndexOutOfRange.
image

1.29 Do not delete last column, if min value in it!
image

Do not use "magic numbers"! Use constants or variables instead. Or GetLength command. So it would be easier to change size. Only in ome place instead of everything!
image

And when you want to create a line of values, use Write instad of WriteLine

3.1 Doesn't work
image
image

3.8 Doesn't work with 0th elements?
image

3.10 Do not use 3-nested loops
image

3.11 Doesn't work
image

**Comment by NemirovichMark** [comment]
Hello Michail.

1.29 Wrong min detection.
image

Everything else is correct 👍

**Comment by NemirovichMark** [comment]
Hello. No, ploblem is not in sign.

image

**Comment by MichailSitnikov** [comment]
How it works now:
Dell
Last not del

**Comment by NemirovichMark** [comment]
Great!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
