### PR TITLE
Lab_4

### PR DESCRIPTION
**Pull request by PankovDaniil**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Daniil.

Do not use "magic numbers", please. Sometimes you do. It will be difficult to change program in the future.

3.1 Do not use 3-nested loops, please. Your program have to execute step by step. Do not try to make everything at once.
image

3.8 The same

3.10 The same

**Comment by PankovDaniil** [comment]
Check,pls

**Comment by NemirovichMark** [comment]
Well done!

**Comment by NemirovichMark** [comment]
You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
