### PR TITLE
Lab_4

### PR DESCRIPTION
**Pull request by TimKonstantinov**
Hello, Mark! This is my Lab_4

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Tim.

1.12 It is bad to use "magic numbers". Either use constants/variables that declare matrix size, or array.GetLength(0 or 1);
for (int i = maxi; i < 5; i++)
                for (int j = 0; j < 7; j++)
                    M[i, j] = M[i + 1, j];
            for (int i = 0; i < 5; i++)
                for (int j = maxj; j < 6; j++)
                    M[i, j] = M[i, j + 1];
            for (int i = 0; i < 5; i++)

And you didn't remove the row and column. You shift the values and hide the last row and column.

1.29 The same.

3.1 a) You sort in ascending order, but required in descending.
b) it breaks if there is 2 rows with equal min element:
image

3.11 Expected that wouldn't lines with zeros at all. And have to work with any matrix.
image

image

image

**Comment by TimKonstantinov** [comment]
Hello, Mark! I fixed my bugs.

**Comment by NemirovichMark** [comment]
Hello Tim.

3.1 You use 3-nested loop:
image

It is not permitted (in that case at least).
Do not try to do everything at once. Separate work of your program to stages and do them step by step.

3.11 It seems that error leads to 0 0 output
image
&
image

**Comment by TimKonstantinov** [comment]
Hello, Mark. I fixed it again.

**Comment by NemirovichMark** [comment]
Hello.
Yeah!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms:
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
