### PR TITLE
4-th lab

### PR DESCRIPTION
**Pull request by Mihail-Shalyrin**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Mikhail.

1.12 Max is not max sometimes.
image

1.17 Read the task more attentively
image

3.1 & 3.8 & 3.10 & 3.11 Do not use 3-nested loops, please.
image

**Comment by Mihail-Shalyrin** [comment]
please check my work

**Comment by Mihail-Shalyrin** [comment]
the last file contains fixed 11 task of 3-rd part

**Comment by NemirovichMark** [comment]
Hello Mikhail.

1.12 👍 

1.17 👍 

3.1 & 3.8 & 3.10 It is still 3-nested loop. It doens't matter what type of the loop you use (do/whileforforeach)
image

3.11 👍

**Comment by Mihail-Shalyrin** [comment]
can i use a methods  with a 3-nestes loops for sort arrays ?

**Comment by NemirovichMark** [comment]
Nope.

You have to separate your code so that actions would be made step by step. Do not try to do everything in one place.

**Comment by Mihail-Shalyrin** [comment]
is it possible to use "buble sorting"?

**Comment by Mihail-Shalyrin** [comment]
for two-dimensional array

**Comment by Mihail-Shalyrin** [comment]
i did this correctly

**Comment by Mihail-Shalyrin** [comment]
maybe

**Comment by NemirovichMark** [comment]
> 

It is better to transform matrix to array, sort it and convert to matrix

**Comment by NemirovichMark** [comment]
Hello Mikhail.

3.1 Not working if there is same index, I suppose.
image

3.8 👍 

3.10 👍

**Comment by Mihail-Shalyrin** [comment]
and again

**Comment by NemirovichMark** [comment]
Hello Mikhail.
When you asked me can you make separate method, I answered: "No". 
image
image

You can solve it in 2 ways:
1)
create a matrix (or 2 arrays) with max element value and it' index
sort this matrix
create new output matrix and fill it with elements form input matrix in sorted order
2)
use Gnome sort instead bubble

**Comment by Mihail-Shalyrin** [comment]
i fixed again

**Comment by NemirovichMark** [comment]
Hello Mikhail.

Well done!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
