### PR TITLE
Create My_4th_Lab

### PR DESCRIPTION
**Pull request by KovalyukYliana**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
image

Hello Yliana.
Use less than 3 nested-cycle.
In the 3rd level.

**Comment by KovalyukYliana** [comment]
I corrected tasks

**Comment by NemirovichMark** [comment]
Hello Yliana.

3.1 & 3.8 Still 3-nested loop
image

3.11 The same. You can create a new matrix and fill it, actually ;)
image


Your program should not try to do everything at once. Better to do work step by step. Please, rework it with such work-flow: firstly input, than findind indexes and values, then sorting.

**Comment by NemirovichMark** [comment]
Well done!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
