### PR TITLE
4th_Lab

### PR DESCRIPTION
**Pull request by unsaid-azizov**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Said.

Good job in general. 

In 3.1 you mess the order if equal min elements in the different lines. Fix it.
image

**Comment by unsaid-azizov** [comment]
I created a separate file for 3_1, please check it out ))

**Comment by NemirovichMark** [comment]
Hello.

Still the problem here:
image

**Comment by unsaid-azizov** [comment]
Mark Anatolevich, sorry, there was a misunderstanding about the essence of the problem, so now problem is fixed!
image

**Comment by NemirovichMark** [comment]
Good!

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
