### PR TITLE
lab №4

### PR DESCRIPTION
**Pull request by EgorPetko**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Egor.

static void exercise_2_9() You reverse all matrix. Not an each row separately. Actually you can do it directly after typing.
B[i, j] = A[n - i - 1, m - j - 1]; 

static void exercise_3_10() Do not use 3 nested cycle
for (int i = 0; i < n; i++)
            {
                for (int j = 0; j < m; j++)
                {
                    for (int k = j; k < m; k++)

**Comment by EgorPetko** [comment]
update

**Comment by NemirovichMark** [comment]
Good Job.

I will send you a link to next lab later.

**Comment by NemirovichMark** [comment]
You can come to class to defend 4th lab.
You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
