### PR TITLE
lab 4(if u cant see my cs file write plz)

### PR DESCRIPTION
**Pull request by PokotiloAndrey**
I guess i need to write here about lab 4.

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Artem.

I found your file. I will check your work partially and write about error in separate messages.

Advice: when you have to find indes, use -1 as initial instead of
double imin = 1000;
And check after search to (index != -1)

**Comment by NemirovichMark** [comment]
2.7 & 2.8 Do not use 3-nested loops. KISS - keep it simple, student

Screenshot_20221117_170435_com android chrome

Screenshot_20221117_170416_com android chrome

**Comment by NemirovichMark** [comment]
1.12 Wrong output
image

**Comment by NemirovichMark** [comment]
3.1 Your program has to work well with any input
image

**Comment by NemirovichMark** [comment]
Everything else is good

**Comment by PokotiloAndrey** [comment]
Hi. I am sorry my name is Andrey. I uploaded fixed lab 4. Check again plz

**Comment by NemirovichMark** [comment]
Oh, Sorry Andrey.
I check the Tereshkin Artem's works in a parallel.
Seems, mess a little bit.

**Comment by NemirovichMark** [comment]
1.12 👍 

2.7 👍 

2.8 👍 

3.1 Not yet
image
image

**Comment by NemirovichMark** [comment]
image

**Comment by PokotiloAndrey** [comment]
ok.that was hard, but i guess i fixed it. i want to think that it will be last check

**Comment by NemirovichMark** [comment]
Hello Andrey.

It is cunning solution. But it doens't work with large matrixes:
image

And you change the order. That is not right, please, use own sort for that purpose

**Comment by PokotiloAndrey** [comment]
Hello again. Well that was bad, but  i rewrote it with another sorting method. Now i guess it's better. I uploaded file with it.

**Comment by NemirovichMark** [comment]
Hello Andrey.

Good job! 👍 

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms (for my choice):
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
