### PR TITLE
This is Lab4

### PR DESCRIPTION
**Pull request by SamikovaElena**

### CODE REVIEW

**Comment by SamikovaElena** [comment]
this is lab4

**Comment by NemirovichMark** [comment]
Hello Elena.

1.12 The output array have to be [5,6]. In your case it still [6,7] with shifted and skipped row and column.

3.1 Doesn't work
image

3.11 Why?
image
image
image
image
image

**Comment by SamikovaElena** [comment]
New lab4

**Comment by SamikovaElena** [comment]
I fixed Lab4

**Comment by NemirovichMark** [comment]
Good job.

Sorry for delay.

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms:
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
