### PR TITLE
hello, 4 lab

### PR DESCRIPTION
**Pull request by Alexey-Khviatskovich**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Alexey.

1.13 No need in 2nd cycle and if-statement. You have to seek only on diagonal.
for (int k = 0; k < n; k++)
                {
                    for (int j = 0; j < m; j++)
                    {
                        if (k == j)
                        {
                            if (matrix_in_use[k, j] > biggest_value)
                            {

1.29 You miss the column (last) instead removing it. So, remake the task, please, with resizing.

2.7 The same as 1.13

3.1 Do not use 3-nested cycles. 2 - maximum!
3.8 The same

3.11 Do not use 4-nested cycles. 2 - maximum!

**Comment by Alexey-Khviatskovich** [comment]
задания 3.1 и 3.8 у меня сделаны по сути одним и тем же способом, я шёл к нему очень долго. Я ни один час пытался разбить на несколько циклов, но я не представляю, как это сделать. Я не знаю, как сделать без 3ёх вложений.

**Comment by NemirovichMark** [comment]
Hello.
You can look how it did your groupmates in their branches. But you have to understand how they did it instead just crtl+c & ctrl+v. 

But it is simpler that you think.
Divide task for 3 part:
For example look at 3.1
1) You have to create a matrix that include index of the row and minimum value in it.
[0 -5]
[1 -4]
[2 -9]
[3 2]
...
2) Sort this matrix
3) Swap the lines in the input matrix so as they presented in the index-matrix

P.S. You can use Tuple instead matrix
(0, -5)
(1, -4)
...
Or List, Queue, Stack...

The main thing - you have to understand how does it work.

**Comment by NemirovichMark** [comment]
Hello.

1.29 IndexOutOfRange
image

3.1 Better, but answer is wrong yet
image

3.11 Expected that you REMOVE the rows. But you make them zeros. Remake.
image

**Comment by Alexey-Khviatskovich** [comment]
3.1 работает на моём компе

**Comment by Alexey-Khviatskovich** [comment]
[https://sun9-1.userapi.com/impg/sDNVvZWomOCbt_Ctq2GELrJ6Vt08i3jhMcjirg/l3emQ3Izi38.jpg?size=1366x840&quality=95&sign=2a997729915edcfa23924fa95fcacf71&type=album](url)

**Comment by Alexey-Khviatskovich** [comment]
фото на почте

**Comment by Alexey-Khviatskovich** [comment]
3_1 работает у меня

вт, 25 окт. 2022 г. в 19:17, Mark ***@***.***>:

**Comment by NemirovichMark** [comment]
3.1 Works with mistake:
image

**Comment by NemirovichMark** [comment]
1.29 & 3.11 Work well.

**Comment by Alexey-Khviatskovich** [comment]
вроде починил

**Comment by Alexey-Khviatskovich** [comment]
было бы круто, если вы бы проверили сегодня и я защитил бы завтра

**Comment by NemirovichMark** [comment]
Hello Alexey. Of course, I will. You wait it so long.

You can come to class to defend 4th lab.

On the defend I will ask you to use sort by one of the follow algorithms:
Shake (coctail)
Insert
Gnome
Shell's
(if you want):
Merge
Quick
Radix

You can make a fork of next lab and send the request to your branch:
https://github.com/NemirovichMark/5th_Lab

**Pull request merged**
